<?php
//
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Coba extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Coba_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'coba/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'coba/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'coba/index.html';
            $config['first_url'] = base_url() . 'coba/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Coba_model->total_rows($q);
        $coba = $this->Coba_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'coba_data' => $coba,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('coba/coba_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Coba_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_coba' => $row->id_coba,
		'nama_coba' => $row->nama_coba,
	    );
            $this->load->view('coba/coba_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('coba'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('coba/create_action'),
	    'id_coba' => set_value('id_coba'),
	    'nama_coba' => set_value('nama_coba'),
	);
        $this->load->view('coba/coba_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_coba' => $this->input->post('nama_coba',TRUE),
	    );

            $this->Coba_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('coba'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Coba_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('coba/update_action'),
		'id_coba' => set_value('id_coba', $row->id_coba),
		'nama_coba' => set_value('nama_coba', $row->nama_coba),
	    );
            $this->load->view('coba/coba_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('coba'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_coba', TRUE));
        } else {
            $data = array(
		'nama_coba' => $this->input->post('nama_coba',TRUE),
	    );

            $this->Coba_model->update($this->input->post('id_coba', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('coba'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Coba_model->get_by_id($id);

        if ($row) {
            $this->Coba_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('coba'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('coba'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_coba', 'nama coba', 'trim|required');

	$this->form_validation->set_rules('id_coba', 'id_coba', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Coba.php */
/* Location: ./application/controllers/Coba.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-01-11 03:35:49 */
/* http://harviacode.com */