<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Expedisi_model extends CI_Model
{

    public $table = 'expedisi';
    public $id = 'id_expedisi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
// Fungsi untuk melakukan proses upload file
	public function upload(){
		$config['upload_path'] = './data_expedisi/';
		$config['allowed_types'] = 'jpg|png|jpeg|doc|docx|xls|xlsx|pdf';
		$config['max_size']	= '200000';
       // $config['quality']= '50%';
		$config['remove_space'] = TRUE;
        $config['overwrite']=TRUE;
        config['max_width'] = 1080; // batas lebar gambar dalam piksel
        $config['max_height'] = 1080; // batas tinggi gambar dalam piksel

		$this->load->library('upload', $config); // Load konfigurasi uploadnya
		if($this->upload->do_upload('file')){ // Lakukan upload dan Cek jika proses upload berhasil
			// Jika berhasil :
			$return = array('result' => 'success', 'file' => $this->upload->data(), 'error' => '');
			return $return;
		}else{
			// Jika gagal :
			$return = array('result' => 'failed', 'file' => '', 'error' => $this->upload->display_errors());
			return $return;
		}
	}
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_expedisi', $q);
	$this->db->or_like('kepada', $q);
	$this->db->or_like('kurir', $q);
	$this->db->or_like('resi', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('file', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_expedisi', $q);
	$this->db->or_like('kepada', $q);
	$this->db->or_like('kurir', $q);
	$this->db->or_like('resi', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('file', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
	// Fungsi untuk menyimpan data ke database
	public function save(){
	$upload = $this->Expedisi_model->upload();
	
	$data = array(
		'kepada' => $this->input->post('kepada',TRUE),
		'kurir' => $this->input->post('kurir',TRUE),
		'resi' => $this->input->post('resi',TRUE),
		'tanggal' => $this->input->post('tanggal',TRUE),
		'keterangan' => $this->input->post('keterangan',TRUE),
		'file' => $upload['file']['file_name'],
		'status' => $this->input->post('status',TRUE),
	    );
		
		$this->db->insert('expedisi', $data);
	}

}

/* End of file Expedisi_model.php */
/* Location: ./application/models/Expedisi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-23 10:23:34 */
/* http://harviacode.com */