<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Karyawan_model extends CI_Model
{

    public $table = 'karyawan';
    public $id = 'id_karyawan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
	// Fungsi untuk melakukan proses upload file
	public function upload(){
		$config['upload_path'] = './foto_karyawan/';
		$config['allowed_types'] = 'jpg|png|jpeg|doc|docx|xls|xlsx|pdf';
		$config['max_size']	= '200000';
		$config['remove_space'] = TRUE;
		$this->load->library('upload', $config); // Load konfigurasi uploadnya
		if($this->upload->do_upload('file')){ // Lakukan upload dan Cek jika proses upload berhasil
			// Jika berhasil :
			$return = array('result' => 'success', 'file' => $this->upload->data(), 'error' => '');
			return $return;
		}else{
			// Jika gagal :
			$return = array('result' => 'failed', 'file' => '', 'error' => $this->upload->display_errors());
			return $return;
		}
	}
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
	$this->db->order_by($this->id, $this->order);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($q = NULL) {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
		// Fungsi untuk menyimpan data ke database
	public function save(){
		include "cryptz.php";
	$upload = $this->Karyawan_model->upload();
	
	$data = array(
		'nama_karyawan' => md5_encrypt($this->input->post('nama_karyawan',TRUE)),
		'nik' => md5_encrypt($this->input->post('nik',TRUE)),
		'jenis_kelamin' => $this->input->post('jenis_kelamin',TRUE),
		'tgl_masuk_kerja' => md5_encrypt($this->input->post('tgl_masuk_kerja',TRUE)),
		'jabatan' => md5_encrypt($this->input->post('jabatan',TRUE)),
		'tgl_lahir' => md5_encrypt($this->input->post('tgl_lahir',TRUE)),
		'nama_ibu_kandung' => md5_encrypt($this->input->post('nama_ibu_kandung',TRUE)),
		'status' => $this->input->post('status',TRUE),
		'jumlah_anak' => $this->input->post('jumlah_anak',TRUE),
		'alamat' => md5_encrypt($this->input->post('alamat',TRUE)),
		'no_hp' => md5_encrypt($this->input->post('no_hp',TRUE)),
		'keterangan' => md5_encrypt($this->input->post('keterangan',TRUE)),
		'foto' => md5_encrypt($upload['file']['file_name']),
		'status_aktif' => $this->input->post('status_aktif',TRUE),
	    );
		
		$this->db->insert('karyawan', $data);
	}

}

/* End of file Karyawan_model.php */
/* Location: ./application/models/Karyawan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-14 04:26:52 */
/* http://harviacode.com */