<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kategori_iso_model extends CI_Model
{

    public $table = 'kategori_iso';
    public $id = 'id_kategori_iso';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_kategori_iso,nama_kategori_iso,ket');
        $this->datatables->from('kategori_iso');
        //add this line for join
        //$this->datatables->join('table2', 'kategori_iso.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('kategori_iso/read/$1'),'Read')." | ".anchor(site_url('kategori_iso/update/$1'),'Update')." | ".anchor(site_url('kategori_iso/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_kategori_iso');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kategori_iso', $q);
	$this->db->or_like('nama_kategori_iso', $q);
	$this->db->or_like('ket', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kategori_iso', $q);
	$this->db->or_like('nama_kategori_iso', $q);
	$this->db->or_like('ket', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kategori_iso_model.php */
/* Location: ./application/models/Kategori_iso_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-01-25 05:08:23 */
/* http://harviacode.com */